v-edit-php return fix

diff --git a/bin/v-edit-domain-php-ini b/bin/v-edit-domain-php-ini
--- a/bin/v-edit-domain-php-ini
+++ b/bin/v-edit-domain-php-ini
@@ -73,7 +73,10 @@ echo "Restarting PHP-FPM service for PHP version ${fpm_ver}"
 systemctl restart php${fpm_ver}-fpm
 if [ $? -ne 0 ]; then
     systemctl status php${fpm_ver}-fpm
-    check_result $E_RESTART "ERROR: php${fpm_ver}-fpm restart failed - please re-run the command and fix the problem !!!"
+    echo "========================="
+    echo ""
+    echo "ERROR: php${fpm_ver}-fpm restart failed - please re-run the command and fix the problem !!!"
+    exit $E_RESTART;
 else
     echo "The PHP-FPM service for PHP version ${fpm_ver} has been restarted successfully."
 fi
diff --git a/bin/v-edit-php-ini b/bin/v-edit-php-ini
--- a/bin/v-edit-php-ini
+++ b/bin/v-edit-php-ini
@@ -54,7 +54,10 @@ echo "Restarting the PHP-FPM service for PHP version $php_version..."
 systemctl restart php${php_version}-fpm
 if [ $? -ne 0 ]; then
     systemctl status php${php_version}-fpm
-    check_result $E_RESTART "ERROR: php${php_version}-fpm restart failed - please re-run the command and fix the problem !!!"
+    echo "========================="
+    echo ""
+    echo "ERROR: php${php_version}-fpm restart failed - please re-run the command and fix the problem !!!"
+    exit $E_RESTART;
 else
     echo "The PHP-FPM service for PHP version ${php_version} has been restarted successfully."
 fi
