v-move-domain-and-database-to-account: Update wordfence-waf.php
Update v-move-domain-and-database-to-account

Update v-delete-web-domain: deleting /hdd/home/$user/web/$domain

Update v-delete-user: deleting /hdd/home/$user

Update v-delete-mail-domain: removing /hdd/home/$user/mail/$domain_idn

Update v-change-domain-owner: moving /hdd/home/$owner/web/$domain

Update v-change-domain-owner: moving /hdd/home/$owner/mail/$domain

Update v-move-folder-and-make-symlink: debug and additional checking

diff --git a/bin/v-move-domain-and-database-to-account b/bin/v-move-domain-and-database-to-account
--- a/bin/v-move-domain-and-database-to-account
+++ b/bin/v-move-domain-and-database-to-account
@@ -92,31 +92,51 @@ fi
 #               Update Wordfence WAF Path                  #
 #----------------------------------------------------------#
 
-# Path to .user.ini file
-user_ini="$USER_DATA/web/$domain/public_html/.user.ini"
+filepath="/home/USER_TO/web/$domain/public_html/.user.ini"
+filename=$(basename $filepath)
 
-# Check if .user.ini exists
-if [ -f "$user_ini" ]; then
-    echo "Updating .user.ini with new user path..."
+# Check if file exists
+if [ -f "$filepath" ]; then
+    echo "Updating $filename with new user path..."
     
     # Temporary file for modification
     tmp_file=$(mktemp)
     
     # Change path from old USER to new USER_TO
-    sed "s|/home/$owner/public_html|/home/$USER_TO/public_html|g" "$user_ini" > "$tmp_file"
+    sed "s|/home/$owner/public_html|/home/$USER_TO/public_html|g" "$filepath" > "$tmp_file"
     
-    # Check if replacement was successful and update .user.ini
+    # Check if replacement was successful and update file
     if [ $? -eq 0 ]; then
-        mv "$tmp_file" "$user_ini"
-        echo ".user.ini updated successfully."
+        mv "$tmp_file" "$filepath"
+        echo "$filename updated successfully."
     else
-        echo "Failed to update .user.ini file."
+        echo "Failed to update $filename file."
         rm "$tmp_file"  # Deletes temporary file
     fi
-else
-    echo ".user.ini does not exist, no changes made."
 fi
 
+filepath="/home/USER_TO/web/$domain/public_html/wordfence-waf.php"
+filename=$(basename $filepath)
+
+# Check if file exists
+if [ -f "$filepath" ]; then
+    echo "Updating $filename with new user path..."
+    
+    # Temporary file for modification
+    tmp_file=$(mktemp)
+    
+    # Change path from old USER to new USER_TO
+    sed "s|/home/$owner/public_html|/home/$USER_TO/public_html|g" "$filepath" > "$tmp_file"
+    
+    # Check if replacement was successful and update file
+    if [ $? -eq 0 ]; then
+        mv "$tmp_file" "$filepath"
+        echo "$filename updated successfully."
+    else
+        echo "Failed to update $filename file."
+        rm "$tmp_file"  # Deletes temporary file
+    fi
+fi
 
 #----------------------------------------------------------#
 #                       Vesta                              #
diff --git a/bin/v-move-folder-and-make-symlink b/bin/v-move-folder-and-make-symlink
--- a/bin/v-move-folder-and-make-symlink
+++ b/bin/v-move-folder-and-make-symlink
@@ -19,12 +19,24 @@ fi
 FROMFOLDER=$1
 TOFOLDER=$2
 
+echo "Executing: v-move-folder-and-make-symlink $1 $2"
+
 # Includes
 source $VESTA/func/main.sh
 
 #----------------------------------------------------------#
 #                    Verifications                         #
 #----------------------------------------------------------#
+
+if [ -z "$FROMFOLDER" ]; then
+    echo "First parameter is empty, aborting"
+    exit 1
+fi
+
+if [ -z "$TOFOLDER" ]; then
+    echo "Second parameter is empty, aborting"
+    exit 1
+fi
 
 # Trimming the ending slash, just in case
 FROMFOLDER=$(echo "$FROMFOLDER" | sed 's:/*$::')
